// <auto-generated />
using System;
using AdvertisementService.Infrastructure.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdvertisementService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251010033338_addIntitial")]
    partial class addIntitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdvertisementService.Domain.Entities.AdvertisementMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdvertisementPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MediaType")
                        .HasColumnType("int");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdvertisementPostId");

                    b.ToTable("AdvertisementMedias");
                });

            modelBuilder.Entity("AdvertisementService.Domain.Entities.AdvertisementPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxPostCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("AdvertisementPackages");
                });

            modelBuilder.Entity("AdvertisementService.Domain.Entities.AdvertisementPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("PackagePurchaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("PackagePurchaseId");

                    b.HasIndex("PartnerId");

                    b.ToTable("AdvertisementPosts");
                });

            modelBuilder.Entity("AdvertisementService.Domain.Entities.PartnerPackagePurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PaymentTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RemainingPostCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("PartnerId");

                    b.ToTable("PartnerPackagePurchases");
                });

            modelBuilder.Entity("AdvertisementService.Domain.Entities.AdvertisementMedia", b =>
                {
                    b.HasOne("AdvertisementService.Domain.Entities.AdvertisementPost", "AdvertisementPost")
                        .WithMany("MediaItems")
                        .HasForeignKey("AdvertisementPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdvertisementPost");
                });

            modelBuilder.Entity("AdvertisementService.Domain.Entities.AdvertisementPost", b =>
                {
                    b.HasOne("AdvertisementService.Domain.Entities.PartnerPackagePurchase", "PackagePurchase")
                        .WithMany("AdvertisementPosts")
                        .HasForeignKey("PackagePurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackagePurchase");
                });

            modelBuilder.Entity("AdvertisementService.Domain.Entities.PartnerPackagePurchase", b =>
                {
                    b.HasOne("AdvertisementService.Domain.Entities.AdvertisementPackage", "Package")
                        .WithMany("PartnerPackagePurchases")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("AdvertisementService.Domain.Entities.AdvertisementPackage", b =>
                {
                    b.Navigation("PartnerPackagePurchases");
                });

            modelBuilder.Entity("AdvertisementService.Domain.Entities.AdvertisementPost", b =>
                {
                    b.Navigation("MediaItems");
                });

            modelBuilder.Entity("AdvertisementService.Domain.Entities.PartnerPackagePurchase", b =>
                {
                    b.Navigation("AdvertisementPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
