version: '3.8'

services:
  apigateway:
    build:
      context: ./src/gateway
      dockerfile: Dockerfile
    container_name: apigateway
    ports:
      - "5120:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - authservice   # đảm bảo gateway chạy sau khi authservice đã start
    networks:
      - travelnet

  authservice:
    build:
      context: ./src/services/AuthService
      dockerfile: Dockerfile
    container_name: authservice
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - travelnet

networks:
  travelnet:
    driver: bridge
