version: '3.8'
services:
  apigateway:
    build:
      context: ./src/gateway
      dockerfile: Dockerfile
    container_name: apigateway
    ports:
      - "5120:80"
    depends_on:
      - userservice
    networks:
      - travelnet

  userservice:
    build:
      context: ./src/services/UserService
      dockerfile: Dockerfile
    container_name: userservice
    ports:
      - "5001:80"
    networks:
      - travelnet

networks:
  travelnet:
    driver: bridge
